apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "gcp-demo1-all-data-tuned"
  namespace: kubeflow
spec:
  cleanPodPolicy: None 
  tfReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: ExitCode
      template:
        spec:
          containers:
            - name: tensorflow
              image: gcr.io/ml-sandbox-1-191918/gcp-demo1:training
              imagePullPolicy: Always
              command:
                - "python"
                - "-m"
                - "trainer.task"
                - "--batch-size=102400"
                - "--epochs=12"
                - "--cycle-length=14"
                - "--job-dir=gs://gcp-cert-demo-1/model/output"
                - "--table-id=finaltaxi_encoded"
                - "--summary-write-steps=10"
                - "--log-step-count-steps=5"
                - "--learning-rate=0.01"
                - "--dropout-rate=0.0"
                - "--optimizer=rmsprop"
              resources:
                limits:
                  cpu: '14'
                  memory: '100G'
              env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/etc/secrets/user-gcp-sa.json"
              volumeMounts:
              - name: sa
                mountPath: "/etc/secrets"
                readOnly: true
          volumes:
          - name: sa
            secret:
              secretName: user-gcp-sa